In [1]:
import numpy as np
import pandas as pd

Creating a random numpy array

In [68]:
a = np.random.randn(3,3)
print(a)
print(a.shape)
print(a.dtype)

[[-0.79638699 -0.31916049 -0.07329581]
 [ 1.89910606  0.58844025  0.88692925]
 [-1.70283569 -0.79473699 -1.15184422]]
(3, 3)
float64


Changing the datatype to float

In [36]:
a = a.astype("float32")
print(a)
print(a.dtype)

[[-1.1496942  -1.6330885  -1.2107875 ]
 [ 0.09361812  1.4817097  -0.671755  ]
 [ 0.26558238  0.7615343   0.9317649 ]]
float32


Changing the datatype to complex

In [37]:
a = a.astype("complex")
print(a)

print(a.dtype)

[[-1.1496942 +0.j -1.63308847+0.j -1.21078753+0.j]
 [ 0.09361812+0.j  1.48170972+0.j -0.67175502+0.j]
 [ 0.26558238+0.j  0.76153427+0.j  0.9317649 +0.j]]
complex128


Creating another numpy array for operations

In [38]:
b  = np.random.rand(3,3)
print(b)

[[0.40641049 0.43406995 0.44386638]
 [0.90628253 0.33497919 0.74118868]
 [0.72061417 0.69118907 0.22174452]]


Making both the array uniform 

In [39]:
a = a.astype("float")
b = b.astype("float")
print(a)
print(b)

[[-1.1496942  -1.63308847 -1.21078753]
 [ 0.09361812  1.48170972 -0.67175502]
 [ 0.26558238  0.76153427  0.9317649 ]]
[[0.40641049 0.43406995 0.44386638]
 [0.90628253 0.33497919 0.74118868]
 [0.72061417 0.69118907 0.22174452]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


Adding numpy arrays

In [40]:
c = np.add(a,b)
print(c)

[[-0.74328371 -1.19901852 -0.76692115]
 [ 0.99990066  1.81668891  0.06943366]
 [ 0.98619655  1.45272334  1.15350942]]


Transposing numpy arrays

In [41]:
print(a.T)
print(b.T)

[[-1.1496942   0.09361812  0.26558238]
 [-1.63308847  1.48170972  0.76153427]
 [-1.21078753 -0.67175502  0.9317649 ]]
[[0.40641049 0.90628253 0.72061417]
 [0.43406995 0.33497919 0.69118907]
 [0.44386638 0.74118868 0.22174452]]


Applying dot product b/w two numpy matrices

In [43]:
d = np.dot(a,b)
print(d)

[[-2.81979799 -1.88298147 -1.9892228 ]
 [ 0.89681884  0.07266902  0.99082241]
 [ 1.46954367  1.01440518  0.88893744]]


Accessing matrix elements i.e rows and columns , slicing and reversing

In [54]:
# Accessing rows
d[:,:]

array([[-2.81979799, -1.88298147, -1.9892228 ],
       [ 0.89681884,  0.07266902,  0.99082241],
       [ 1.46954367,  1.01440518,  0.88893744]])

In [55]:
# Accessing columns
d[:3,:1]

array([[-2.81979799],
       [ 0.89681884],
       [ 1.46954367]])

In [56]:
#slicing bottom right of the matrix
d[1:,1:]

array([[0.07266902, 0.99082241],
       [1.01440518, 0.88893744]])

Accessing dataset from online and importing data to numpy array

In [62]:
df = pd.read_csv("/content/sample_data/mnist_test.csv")
df.head()

7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  2  0    0    0    0    0  ...      0      0      0      0      0      0
1  1  0    0    0    0    0  ...      0      0      0      0      0      0
2  0  0    0    0    0    0  ...      0      0      0      0      0      0
3  4  0    0    0    0    0  ...      0      0      0      0      0      0
4  1  0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 785 columns]

Changing pandas dataframe to numpy array

In [64]:
df_numpy= np.array(df)
df_numpy

array([[2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0]])

Confirming the datatype of the numpy array

In [67]:
print(type(df_numpy))
df_numpy.dtype

<class 'numpy.ndarray'>


dtype('int64')